### ISSUE TITLE
OpenModelica support

### ISSUE THREAD

**Issue by AnHeuermann** [xrg-simulation/SMArtIInt#1]
Hey XRG 👋 

We tried to use this library with OpenModelica. So first we gave this repository a quick try with Dymola and could simulate all examples. The reference models seem to work in OpenModelica as well.

When trying to simulate the test cases with OpenModelica we encountered multiple issues.
I opened `SMArtIInt\\package.mo` in OMEdit, so I didn't use the `DymolaStartup.mos`:

- [x] Variable not found
  ```
  [2] 15:39:09 Translation Error
  [SMArtIInt.Internal.Utilities.RunInterferenceRNN: 34:5-34:8]: Variable y not found in scope RunInterferenceRNN.
  ```
  e.g. `SMArtIInt.Tester.ExamplePI.StepTest_RNN`.
- [x] Invalid connector
  ```
  [2] 15:44:01 Translation Error
  Internal error Invalid connector type on component unit
  ```
  e.g. `SMArtIInt.Tester.PipeHeatTransferExample.TestPipe`.
- [x] Inner declaration missing
  ```
  [3] 15:45:27 Translation Warning
  [Modelica.Fluid.Interfaces: 507:7-507:61]: An inner declaration for outer component system could not be found and was automatically generated.
  ```
  e.g. `SMArtIInt.Tester.ExamplePI.DoubleRoom_RNN`.

## Versions 'n stuff

  - OpenModelica:  OpenModelica v1.20.0-dev-434-g49b8cd72be (64-bit)
  - OS: Windows 11, 64bit
  - SMArtIInt: [debeeaa](https://github.com/xrg-simulation/SMArtIInt/commit/debeeaac4e17e1fba56c6b0450641a598b529e26)

**Comment by RMFlesch** [comment]
Thank you for reporting these issues. The models were modified and the tester do run in OpenModelica now!
