### ISSUE TITLE
Dymola pedantic mode

### ISSUE THREAD

**Issue by AnHeuermann** [xrg-simulation/SMArtIInt#2]
I enabled the pedantic mode in Dymola `Advanced.Modelica.Pedantic=true`
and got some issue for `SMArtIInt.Tester.ExamplePI.StepTest_RNN`

```
Connecting different kinds of variables
when connecting output step.y and controller.u.
```

Additional issues in other models:

- [x] `SMArtIInt.Tester.ExamplePI.DoubleRoom_RNN`
  ```
  Connecting different kinds of variables
  when connecting input controlHeatFlow.Q_flow and controller.y.
  ```
- [ ] `SMArtIInt.Tester.ExamplePI.DoubleRoom_RNN`
  ```
  Use 'redeclare' instead of 'final redeclare', since there are modifiers for components of the class FluidConstants.
  ```
- [x] `SMArtIInt.Tester.PipeHeatTransferExample.TestModelEvaluation`
  ```
  Connecting different kinds of variables
  when connecting output heatTransfer.Expr_Res[1].y and heatTransfer.pipeLocalHeatTransfer.Re[1].
  ```
- [x] `SMArtIInt.Tester.PipeHeatTransferExample.TestPipe`
  ```
  Connecting different kinds of variables
  when connecting output pipe.heatTransfer.Expr_Res[1].y and pipe.heatTransfer.pipeLocalHeatTransfer.Re[1].
  ```

## Related Issues

Probably related to errors reported by OpenModelica in #1.

## Versions 'n stuff

  - Dymola: Version 2022 (64-bit), 2021-04-14
  - SMArtIInt: [debeeaa](https://github.com/xrg-simulation/SMArtIInt/commit/debeeaac4e17e1fba56c6b0450641a598b529e26)

**Comment by RMFlesch** [comment]
All issues except for the second have been adressed in the latest releases. The second issues seems to be caused by the media models from the MSL.
